# Aula 1 - Primeiros passos com o BigQuery no Google Colab
*   Baseado no notebook https://colab.research.google.com/notebooks/bigquery.ipynb

*   Execute os passos abaixo, conforme explicado nos slides:
1.   Use o [Cloud Resource Manager](https://console.cloud.google.com/cloud-resource-manager) para **criar um projeto na Google Cloud Platform (GCP)**, se você ainda não tem um.
2.   [Habilite as APIs do BigQuery](https://console.cloud.google.com/flows/enableapi?apiid=bigquery) para o projeto.

### Forneça suas credenciais para o ambiente de execução

In [1]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

# Use o BigQuery via magics commands

A biblioteca do bigquery `google.cloud.bigquery` também inclui um magic command que roda uma query e retorna um `DataFrame`.

In [2]:
# Salva o output numa variavel do tipo dataframe 
# enap-331414 é o project id do meu projeto no GPC
# Defina o id do seu projeto no bigquery!!!!!!!!!

%%bigquery --project enap-331414 df
select * from `basedosdados.br_ibge_populacao.municipio` limit 10

In [ ]:
df

    ano sigla_uf id_municipio  populacao
0  1991       RO      1100015      31981
1  1992       RO      1100015      34768
2  1993       RO      1100015      37036
3  1994       RO      1100015      39325
4  1995       RO      1100015      41574
5  1996       RO      1100015      33471
6  1997       RO      1100015      25009
7  1998       RO      1100015      24793
8  1999       RO      1100015      25025
9  2000       RO      1100015      26533

# Use o BigQuery por meio do pandas-gbq

O `pandas-gbq` é uma biblioteca do pandas. Faz operações básicas, como enviar um DataFrame para o BigQuery. Entretanto, por ser uma bilioteca de terceiros (não google)  pode não implementar todas funcionalidades ou casos de uso do BigQuery.

[Pandas GBQ Documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_gbq.html)

In [3]:
import pandas as pd
## Defina o id do seu projeto no bigquery!!!!!
project_id = 'enap-331414' # Defina o id do seu projeto no bigquery!!!!!
## Defina o id do seu projeto no bigquery!!!!!

df = pd.io.gbq.read_gbq('''
  SELECT data_aplicacao, sigla_uf, id_paciente, vacina, dose FROM `basedosdados.br_ms_vacinacao_covid19.microdados_vacinacao` limit 100
''', project_id=project_id)

df.head()

  data_aplicacao sigla_uf  ... vacina     dose
0     2021-05-12       AC  ...     85  1ª Dose
1     2021-09-15       AC  ...     85  2ª Dose
2     2021-02-25       AC  ...     86  1ª Dose
3     2021-06-04       AC  ...     85  2ª Dose
4     2021-05-15       AC  ...     85  1ª Dose

[5 rows x 5 columns]

### Obs.: Ver atividades